const GREETINGS = {
  km: [
    "រួចរាល់ហើយ សូមវាយអក្សរ។",
    "តើអ្នកចង់ស្ដាប់អ្វី?",
    "សូមវាយអក្សរខ្មែរ។",
    "បម្លែងអក្សរទៅជាសម្លេង។",
    "សម្លេងរបស់អ្នករង់ចាំ។",
    "សូមនិយាយដោយសម្លេង។",
    "វាយអ្វីក៏បាន។",
    "តើខ្ញុំគួរនិយាយអ្វី?",
    "សូមបញ្ចេញគំនិតរបស់អ្នក។",
    "អក្សរចូល សម្លេងចេញ។",
    "វាយខាងក្រោមដើម្បីចាប់ផ្ដើម។",
    "សម្លេងនៅចម្ងាយមួយចុចប៉ុណ្ណោះ។",
    "តើអ្នកចង់និយាយអ្វី?",
    "រួចរាល់ក្នុងការបម្លែងអក្សរ។",
    "សូមវាយ រួចចុចផ្ញើ។",
    "សួស្ដី! តើខ្ញុំគួរអានអ្វី?",
    "រង់ចាំការបញ្ចូលរបស់អ្នក។",
    "សូមដាក់អក្សរនៅទីនេះ។",
    "ពាក្យរបស់អ្នក សម្លេងរបស់យើង។",
    "តើរឿងអ្វីដែលខ្ញុំគួរប្រាប់?",
  ],
  en: [
    "Ready when you are.",
    "What would you like to hear?",
    "Type something to begin.",
    "Let's turn text into speech.",
    "Your voice awaits.",
    "Say it with sound.",
    "Go ahead, type anything.",
    "What should I say?",
    "Speak your mind.",
    "Let's create some audio.",
    "Type it, hear it.",
    "Words become voice here.",
    "Ready to generate speech.",
    "What's on your mind?",
    "Let's hear it.",
    "Paste your text below.",
    "Turn your words into audio.",
    "Start typing to begin.",
    "Your text, our voice.",
    "Let's make it speak.",
    "Type below to get started.",
    "Audio is just a click away.",
    "Let's bring your text to life.",
    "What do you want to say?",
    "Ready to convert text.",
    "Just type and press send.",
    "Hello! What shall I read?",
    "Awaiting your input.",
    "Let's synthesize some speech.",
    "Drop your text here.",
    "Text in, audio out.",
    "Let's get talking.",
    "What would you like spoken?",
    "Feed me some text.",
    "I'll say it for you.",
    "Just type and listen.",
    "Speech generation ready.",
  ],
  zh: [
    "准备好了，请输入。",
    "你想听什么？",
    "输入一些文字开始。",
    "把文字变成语音。",
    "你的声音在等待。",
    "用声音表达。",
    "随便输入什么吧。",
    "我该说什么？",
    "说出你的想法。",
    "让我们创造一些音频。",
    "输入它，听到它。",
    "文字在这里变成声音。",
    "准备生成语音。",
    "你在想什么？",
    "让我们听听吧。",
    "把文字粘贴在下面。",
    "把你的话变成音频。",
    "开始输入吧。",
    "你的文字，我们的声音。",
    "让它开口说话。",
  ],
  fr: [
    "Prêt quand vous l'êtes.",
    "Qu'aimeriez-vous entendre ?",
    "Tapez quelque chose pour commencer.",
    "Transformons le texte en parole.",
    "Votre voix vous attend.",
    "Dites-le avec du son.",
    "Allez-y, tapez n'importe quoi.",
    "Que dois-je dire ?",
    "Exprimez-vous.",
    "Créons de l'audio.",
    "Tapez-le, écoutez-le.",
    "Les mots deviennent voix ici.",
    "Prêt à générer la parole.",
    "À quoi pensez-vous ?",
    "Écoutons ça.",
    "Collez votre texte ci-dessous.",
    "Transformez vos mots en audio.",
    "Commencez à taper.",
    "Votre texte, notre voix.",
    "Faisons-le parler.",
  ],
};

export function getGreeting(language) {
  const list = GREETINGS[language] || GREETINGS.en;
  return list[Math.floor(Math.random() * list.length)];
}

export const PLACEHOLDERS = {
  km: "វាយអក្សរខ្មែរនៅទីនេះ...",
  en: "Type your text here...",
  zh: "在此输入文字...",
  fr: "Tapez votre texte ici...",
};
